"""
SSE streaming endpoint for token-by-token translation output.

The frontend can subscribe to GET /api/stream/translate?source=...&filename=...
to receive translated tokens as they're generated by vLLM.

This creates the ChatGPT-style "typing" effect in the UI.
"""
from __future__ import annotations

import asyncio
import json
import urllib.parse
from typing import AsyncGenerator

from fastapi import APIRouter, Query
from fastapi.responses import StreamingResponse
from loguru import logger

router = APIRouter()


@router.get("/stream/translate")
async def stream_translate(
    source: str = Query(..., description="URL-encoded CUDA source code"),
    filename: str = Query("input.cu", description="Original filename"),
    force_remote: bool = Query(False, description="Force remote model"),
):
    """Stream translation tokens via Server-Sent Events.

    The frontend connects with:
        const es = new EventSource('/api/stream/translate?source=...')

    Events:
        event: token
        data: {"content": "#include"}

        event: done
        data: {"content": "full translated code", "tokens": 1234}

        event: error
        data: {"message": "..."}
    """
    # URL-decode the source
    cuda_source = urllib.parse.unquote(source)

    async def event_generator() -> AsyncGenerator[str, None]:
        try:
            from app.agents.routing import ModelRouter
            from app.analyzers.cuda_analyzer import CudaAnalyzer
            from app.rag.retriever import RAGRetriever

            # Analyze
            yield _format_sse("status", {"state": "analyzing"})

            analyzer = CudaAnalyzer()
            analysis = analyzer.analyze(cuda_source, filename)

            yield _format_sse("status", {
                "state": "analyzed",
                "difficulty": analysis.difficulty_score,
                "patterns": [p.value for p in analysis.patterns],
            })

            # Route
            router_instance = ModelRouter()
            router_instance.reset_counters()
            model_choice = router_instance.route(analysis, force_remote=force_remote)
            model = router_instance.get_model(model_choice)

            # RAG context
            yield _format_sse("status", {"state": "translating", "model": model_choice.value})

            retriever = RAGRetriever()
            try:
                chunks = retriever.retrieve(cuda_source)
                rag_context = "\n\n---\n\n".join(chunks)
            except Exception:
                rag_context = ""

            # Stream tokens
            full_translation = ""
            token_count = 0

            # Try streaming (only vLLM supports it currently)
            if hasattr(model, "translate_stream"):
                async for token in model.translate_stream(cuda_source, rag_context):
                    full_translation += token
                    token_count += 1
                    yield _format_sse("token", {"content": token, "count": token_count})

                    # Small delay for UI smoothness (optional)
                    if token_count % 10 == 0:
                        await asyncio.sleep(0.01)
            else:
                # Non-streaming model (Fireworks) — yield all at once
                translated = await model.translate(cuda_source, rag_context)
                full_translation = translated
                token_count = 1
                # Yield in chunks for UI effect
                chunk_size = max(1, len(translated) // 50)
                for i in range(0, len(translated), chunk_size):
                    chunk = translated[i:i + chunk_size]
                    yield _format_sse("token", {"content": chunk, "count": i // chunk_size + 1})
                    await asyncio.sleep(0.02)

            yield _format_sse("done", {
                "content": full_translation,
                "tokens": model.tokens_used,
                "model": model_choice.value,
                "stub_mode": getattr(model, "used_stub", False),
            })

        except Exception as e:
            logger.exception(f"Streaming translation failed: {e}")
            yield _format_sse("error", {"message": str(e)})

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


def _format_sse(event: str, data: dict) -> str:
    """Format a Server-Sent Event string."""
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"
